[workspace]

members = [
    "aoc2019_utils",
    "aoc2019_day01",
    "aoc2019_day02",
    "aoc2019_day03",
    "aoc2019_day04",
    "aoc2019_day05",
    "aoc2019_day06",
    "aoc2019_day07",
    "aoc2019_day08",
    "aoc2019_day09",
]
